openai.api.key=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
openai.threads.url=https://api.openai.com/v1/threads
openai.assistants.url=https://api.openai.com/v1/assistants
openai.assistant.instructions="You are being provided with data, please use that data to help achieve the goal. Your answers should be based solely on the data that is provided"
openai.user.prompt="What is the capital of Italy?"